# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='illustration',
        ),
    ]
